services:
    db:
        image: postgres
        restart: always
        ports:
            - '5432:5432'
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_PORT: 5432
        volumes:
            - ./pgdata:/var/lib/postgresql/data
    redis:
        image: redis
        ports:
            - '6379:6379'
        volumes:
            - ./redisdata:/data
        restart: always
volumes:
    pgdata:
