services:
  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_PORT: 5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
